version: 2.1

jobs:
  flake8:
    docker:
      - image: circleci/python:2.7.14
    steps:
      - checkout
      - run: pip install flake8 --user
      - run: ~/.local/bin/flake8 agent_packager

  test:
    docker:
      - image: circleci/python:2.7.14
    steps:
      - checkout
      - run: sudo apt-get install libpython-dev
      - run: virtualenv ~/venv
      - run: ~/venv/bin/pip install .
      - run: ~/venv/bin/pip install -r test-requirements.txt
      - run: ~/venv/bin/pytest -sv agent_packager

workflows:
  version: 2
  run_test:
    jobs:
      - flake8
      - test
