apiVersion: v1
kind: Pod
spec:
  containers:
    - name: python
      image: python:2
      resources:
        requests:
          cpu: 1
      command:
      - cat
      tty: true
      securityContext:
        runAsUser: 0
        privileged: true
  nodeSelector:
    instance-type: spot